// -----------------------------------------------------------------------------
// TacticalCameraController
//
// This code was generated by Claude (Anthropic), model: Claude Opus 4.7.
// -----------------------------------------------------------------------------

using NaughtyAttributes;
using UnityEngine;
using UnityEngine.InputSystem;

namespace UC
{

    [RequireComponent(typeof(Camera))]
    public class TacticalCameraController : MonoBehaviour
    {
        [SerializeField]
        private PlayerInput playerInput;

        [Tooltip("MousePosition-type control. Used to read the cursor position for edge panning.")]
        [SerializeField, InputPlayer(nameof(playerInput))]
        private UC.InputControl mouseCursorPosition;

        [Tooltip("Button-type control (e.g. RMB). Held to enable rotation.")]
        [SerializeField, InputButton, InputPlayer(nameof(playerInput))]
        private UC.InputControl rotateButtonControl;

        [Tooltip("Analog directional pan, an alternative to edge panning. NewInput (Vector2) bound to a stick or a WASD 2D composite. X = right/left, Y = forward/back. Set type to None to disable.")]
        [SerializeField, InputPlayer(nameof(playerInput))]
        private UC.InputControl panControl;

        [Tooltip("Zoom control. NewInput bound to <Mouse>/scroll/y (or a +/- axis). Positive zooms in. Set type to None to disable.")]
        [SerializeField, InputPlayer(nameof(playerInput))]
        private UC.InputControl zoomControl;

        [Header("Panning")]
        [Tooltip("Distance from the screen edge (in pixels) that triggers panning.")]
        [SerializeField] private float edgeThickness = 25f;
        [Tooltip("Pan speed at the instant the cursor reaches an edge (world units/sec).")]
        [SerializeField] private float panSpeed = 15f;
        [Tooltip("Maximum pan speed after accelerating (world units/sec).")]
        [SerializeField] private float maxPanSpeed = 60f;
        [Tooltip("How quickly pan speed ramps from base to max (units/sec^2).")]
        [SerializeField] private float panAcceleration = 40f;
        [Tooltip("If true, edge panning is disabled while the rotate button is held.")]
        [SerializeField] private bool suppressPanWhileRotating = true;

        [Header("Rotation")]
        [Tooltip("Degrees of yaw per pixel the cursor is dragged horizontally from the press anchor.")]
        [SerializeField] private float rotateSpeed = 0.3f;
        [Tooltip("Degrees of pitch per pixel the cursor is dragged vertically from the press anchor.")]
        [SerializeField] private float pitchSpeed = 0.3f;
        [Tooltip("Minimum pitch in degrees below horizontal (0 = level).")]
        [SerializeField] private float minPitch = 10f;
        [Tooltip("Maximum pitch in degrees below horizontal.")]
        [SerializeField] private float maxPitch = 80f;
        [Tooltip("If true, moving the mouse up tilts the view down instead of up.")]
        [SerializeField] private bool invertPitch = false;
        [Tooltip("Drag distance (pixels) from the anchor before rotation engages.")]
        [SerializeField] private float rotateDeadzone = 6f;
        [Tooltip("Axis locking behaviour during a rotate drag.\nNever: raw passthrough, both axes straight from the mouse (no axis consideration).\nAlways: commit to one axis for the whole gesture.\nOnce: commit while the drag is straight, but release into free diagonals as soon as it becomes clearly diagonal.")]
        [SerializeField] private AxisLockMode axisLockMode = AxisLockMode.Always;
        [Tooltip("Diagonal release threshold (Once mode): the weaker axis must reach at least this fraction of the stronger one for the drag to count as diagonal and release the lock. Lower = releases more easily.")]
        [Range(0f, 1f)]
        [ShowIf(nameof(ShowDiagonalRelease))]
        [SerializeField] private float axisLockRatio = 0.5f;
        [Tooltip("Hysteresis added to the diagonal release threshold (Once mode) so the release point isn't right at the edge of single-axis drift.")]
        [Range(0f, 0.5f)]
        [ShowIf(nameof(ShowDiagonalRelease))]
        [SerializeField] private float axisLockHysteresis = 0.15f;
        [Tooltip("While locked to a single axis (Always / Once before release), the other axis must overtake the current one by this fraction before the lock switches. Higher = stickier.")]
        [Range(0f, 1f)]
        [ShowIf(nameof(ShowSwitchMargin))]
        [SerializeField] private float axisSwitchMargin = 0.15f;

        [Header("Zoom")]
        [Tooltip("World units of dolly per unit of scroll input.")]
        [SerializeField, ShowIf(nameof(cameraIsPerpective))] private float zoomSpeed = 5f;
        [Tooltip("Closest allowed distance from the screen-center ground point.")]
        [SerializeField, ShowIf(nameof(cameraIsPerpective))] private float minZoom = 10f;
        [Tooltip("Farthest allowed distance from the screen-center ground point.")]
        [SerializeField, ShowIf(nameof(cameraIsPerpective))] private float maxZoom = 80f;
        [Tooltip("Orthographic size change per unit of scroll input (orthographic cameras only).")]
        [SerializeField, HideIf(nameof(cameraIsPerpective))] private float orthoZoomSpeed = 2f;
        [Tooltip("Smallest allowed orthographic size, i.e. most zoomed in (orthographic only).")]
        [SerializeField, HideIf(nameof(cameraIsPerpective))] private float minOrthoSize = 3f;
        [Tooltip("Largest allowed orthographic size, i.e. most zoomed out (orthographic only).")]
        [SerializeField, HideIf(nameof(cameraIsPerpective))] private float maxOrthoSize = 30f;

        [Header("Ground Plane")]
        [Tooltip("World Y height of the plane the camera looks at and orbits around.")]
        [SerializeField] private float groundPlaneY = 0f;

        [Header("Bounds")]
        [Tooltip("Optional. The CAMERA position is clamped to stay inside this BoxCollider. Leave empty to disable.")]
        public BoxCollider boundsCollider { get; set; }
        [Tooltip("Optional. The look-at TARGET (screen-center ground point) is clamped to stay inside this BoxCollider's horizontal footprint. Leave empty to disable.")]
        public BoxCollider targetBoundsCollider { get; set; }

        private Camera cam;
        private float currentPanSpeed;

        // Rotation gesture state (set on button-down, used while held).
        private enum LockAxis { None, Horizontal, Vertical }
        public enum AxisLockMode { Never, Always, Once }
        private bool rotating;          // was the rotate button held last frame
        private Vector2 anchorMouse;    // cursor position when the gesture began
        private Vector3 rotatePivot;    // ground point orbited around for this gesture
        private bool hasRotatePivot;    // false if the center ray missed the plane at press
        private bool rotateEngaged;     // true once the drag has passed the deadzone this gesture
        private bool axisLockReleased;  // Once-mode: true after the drag has gone diagonal
        private float basePitch;        // pitch at gesture start
        private float appliedYaw;       // yaw applied so far this gesture
        private float appliedPitch;     // pitch applied so far this gesture
        private LockAxis lockedAxis = LockAxis.None;

        // Inspector helpers for NaughtyAttributes. The diagonal-release tuning only matters
        // in Once mode; the axis-switch margin matters whenever an axis can be locked.
        private bool ShowDiagonalRelease => axisLockMode == AxisLockMode.Once;
        private bool ShowSwitchMargin => axisLockMode != AxisLockMode.Never;
        private bool cameraIsPerpective
        {
            get
            {
                if (cam == null) cam = GetComponent<Camera>();
                return !cam.orthographic;
            }
        }
        public bool panBorderEnable { get; set; }

        void Awake()
        {
            cam = GetComponent<Camera>();

            rotateButtonControl.playerInput = playerInput;
            mouseCursorPosition.playerInput = playerInput;
            panControl.playerInput = playerInput;
            zoomControl.playerInput = playerInput;

            ResetToDefault();
        }

        void Update()
        {
            bool wantRotate = rotateButtonControl.IsPressed();

            if (wantRotate)
                HandleRotate();
            else
                rotating = false; // gesture ended; next press re-anchors

            // Pan unless we're rotating AND suppression is enabled.
            if ((!wantRotate) || (!suppressPanWhileRotating))
                HandlePan();
            else
                currentPanSpeed = 0f; // not panning this frame: reset the ramp

            HandleZoom();

            // Constrain after movement: keep the look-at target in its box first,
            // then enforce the camera box as the hard limit.
            ClampTargetToBounds();
            ClampToBounds();
        }

        // Recenters the camera so its look-at point sits on the middle of the target bounds
        // box, keeping the current orientation and standoff distance (zoom/framing). Does
        // nothing if there's no target bounds box, or if the camera isn't currently looking
        // at the ground plane.
        [Button("Reset To Default")]
        public void ResetToDefault()
        {
            if (targetBoundsCollider == null) return;
            if (cam == null) cam = GetComponent<Camera>();

            // Current look-at point and how far it is along the view ray (the standoff to keep).
            if (!TryGetGroundPointAtScreenCenter(out Vector3 currentFocus)) return;
            float dist = Vector3.Distance(transform.position, currentFocus);

            // Desired focus: the target box's center, dropped onto the ground plane.
            Vector3 boxCenter = targetBoundsCollider.transform.TransformPoint(targetBoundsCollider.center);
            Vector3 desiredFocus = new Vector3(boxCenter.x, groundPlaneY, boxCenter.z);

            // Same orientation, same distance — just place the rig so the center ray lands
            // on the new focus.
            transform.position = desiredFocus - transform.forward * dist;

            // Respect the configured bounds (the focus is the box center, so the target
            // clamp won't move it; the camera box may still apply).
            ClampTargetToBounds();
            ClampToBounds();
        }

        // --- Panning ------------------------------------------------------------

        void HandlePan()
        {
            // Combine both sources: binary screen-edge input + analog directional input.
            Vector2 input = GetEdgeInput() + panControl.GetAxis2();

            // magnitude scales speed (analog stick respected); direction drives the move.
            // Cap at 1 so stacking edge + stick can't exceed full speed.
            float magnitude = Mathf.Min(input.magnitude, 1f);
            if (magnitude < 1e-4f)
            {
                currentPanSpeed = 0f; // nothing pushing: start slow next time
                return;
            }
            Vector2 dir = input.normalized;

            // Ramp: begin at panSpeed, accelerate toward maxPanSpeed while panning continues.
            if (currentPanSpeed < panSpeed) currentPanSpeed = panSpeed;
            currentPanSpeed = Mathf.Min(currentPanSpeed + panAcceleration * Time.deltaTime, maxPanSpeed);

            // Camera forward/right flattened onto the XZ plane, so panning follows
            // wherever the camera is currently looking.
            Vector3 forward = Flatten(transform.forward);
            Vector3 right = Flatten(transform.right);

            Vector3 move = right * dir.x + forward * dir.y;
            transform.position += move * (currentPanSpeed * magnitude * Time.deltaTime);
        }

        // Binary -1/0/+1 per axis based on how close the cursor is to a screen edge.
        Vector2 GetEdgeInput()
        {
            if (!panBorderEnable) return Vector2.zero;

            // When the game view/window loses focus (clicking the Inspector, another app,
            // etc.) the reported cursor position freezes at its last value, which is usually
            // right inside the edge band, causing endless self-panning. Skip while unfocused.
            if (!Application.isFocused) return Vector2.zero;

            Vector2 mouse = mouseCursorPosition.GetAxis2();

            // Only sample edges while the cursor is inside the game window.
            bool insideWindow = (mouse.x >= 0f) && (mouse.x <= Screen.width) &&
                                (mouse.y >= 0f) && (mouse.y <= Screen.height);
            if (!insideWindow) return Vector2.zero;

            Vector2 input = Vector2.zero; // x = right/left, y = forward/back

            if (mouse.x <= edgeThickness) input.x = -1f;
            else if (mouse.x >= Screen.width - edgeThickness) input.x = 1f;

            if (mouse.y <= edgeThickness) input.y = -1f;
            else if (mouse.y >= Screen.height - edgeThickness) input.y = 1f;

            return input;
        }

        // --- Zoom ---------------------------------------------------------------

        void HandleZoom()
        {
            float scroll = zoomControl.GetAxis();
            if (Mathf.Approximately(scroll, 0f)) return;

            if (cam.orthographic)
            {
                // Orthographic: dollying doesn't change apparent size, so zoom the ortho size
                // instead. Smaller size = more zoomed in, so positive scroll shrinks it.
                cam.orthographicSize = Mathf.Clamp(
                    cam.orthographicSize - scroll * orthoZoomSpeed, minOrthoSize, maxOrthoSize);
                return;
            }

            // Perspective: dolly toward / away from the screen-center ground point, clamped
            // by distance.
            if (!TryGetGroundPointAtScreenCenter(out Vector3 pivot)) return;

            Vector3 toCam = transform.position - pivot;
            float dist = toCam.magnitude;
            if (dist < 1e-4f) return; // degenerate: camera sitting on the pivot

            float newDist = Mathf.Clamp(dist - scroll * zoomSpeed, minZoom, maxZoom);
            transform.position = pivot + toCam * (newDist / dist);
        }
        // --- Rotation -----------------------------------------------------------

        void HandleRotate()
        {
            Vector2 mouse = mouseCursorPosition.GetAxis2();

            // Rising edge: anchor the gesture to the current cursor position and pivot.
            if (!rotating)
            {
                rotating = true;
                anchorMouse = mouse;
                basePitch = GetPitch();
                appliedYaw = 0f;
                appliedPitch = 0f;
                lockedAxis = LockAxis.None;
                rotateEngaged = false;
                axisLockReleased = false;
                hasRotatePivot = TryGetGroundPointAtScreenCenter(out rotatePivot);
            }

            if (!hasRotatePivot) return; // center ray missed the plane at press; nothing to orbit

            Vector2 offset = mouse - anchorMouse;

            // Deadzone gates only the START of the gesture. When the cursor first moves past
            // it, re-anchor here so rotation begins from zero — the deadzone distance is NOT
            // counted toward the rotation amount (which is what made it feel "stuck ahead").
            if (!rotateEngaged)
            {
                if (offset.magnitude < rotateDeadzone) return;
                rotateEngaged = true;
                anchorMouse = mouse;          // re-anchor at the crossing point
                offset = Vector2.zero;        // start from zero this frame
            }

            // Resolve which axis/axes are active. If that flips the active axis — Once
            // releasing into a diagonal, or a single-axis switch — re-anchor so the newly
            // freed axis starts from the current cursor position, instead of snapping in the
            // offset that piled up while it was suppressed. Orientation is preserved.
            LockAxis prevAxis = lockedAxis;
            bool prevReleased = axisLockReleased;

            offset = ResolveAxes(offset);

            bool justReleased = axisLockReleased && !prevReleased;
            bool axisSwitched =
                (prevAxis == LockAxis.Horizontal && lockedAxis == LockAxis.Vertical) ||
                (prevAxis == LockAxis.Vertical && lockedAxis == LockAxis.Horizontal);

            if (justReleased || axisSwitched)
            {
                anchorMouse = mouse;
                basePitch = GetPitch();
                appliedYaw = 0f;
                appliedPitch = 0f;
                return; // no rotation this frame; next frame drives from the fresh anchor
            }

            // Absolute targets relative to the press baseline.
            float targetYaw = offset.x * rotateSpeed;
            float targetPitch = Mathf.Clamp(
                basePitch + (invertPitch ? offset.y : -offset.y) * pitchSpeed,
                minPitch, maxPitch);

            // Apply only the change since last frame (RotateAround is incremental).
            float yawStep = targetYaw - appliedYaw;
            if (!Mathf.Approximately(yawStep, 0f))
            {
                transform.RotateAround(rotatePivot, Vector3.up, yawStep);
                appliedYaw += yawStep;
            }

            float pitchStep = (targetPitch - basePitch) - appliedPitch;
            if (!Mathf.Approximately(pitchStep, 0f))
            {
                transform.RotateAround(rotatePivot, Flatten(transform.right), pitchStep);
                appliedPitch += pitchStep;
            }
        }

        // Maps the raw drag offset to the axes that should be active, zeroing the rest.
        // Three behaviours: Never = raw; Always = one locked axis (with overtake switching);
        // Once = one locked axis until the drag turns diagonal, then raw for the rest.
        Vector2 ResolveAxes(Vector2 offset)
        {
            // Raw passthrough: Never, and Once after it has released into a diagonal.
            if (axisLockMode == AxisLockMode.Never) return offset;
            if (axisLockMode == AxisLockMode.Once && axisLockReleased) return offset;

            float ax = Mathf.Abs(offset.x);
            float ay = Mathf.Abs(offset.y);
            float major = Mathf.Max(ax, ay);

            // No meaningful movement yet (e.g. the exact frame we re-anchored): stay neutral.
            if (major < 1e-4f) return Vector2.zero;

            // Once: release the moment the drag is clearly diagonal. From then on it's raw
            // (handled by the early-out above on subsequent frames).
            if (axisLockMode == AxisLockMode.Once &&
                Mathf.Min(ax, ay) / major >= axisLockRatio + axisLockHysteresis)
            {
                axisLockReleased = true;
                return offset;
            }

            // Commit to a single axis, or maintain it (switching only on a clear overtake).
            if (lockedAxis == LockAxis.Horizontal || lockedAxis == LockAxis.Vertical)
            {
                float margin = 1f + axisSwitchMargin;
                if (lockedAxis == LockAxis.Horizontal)
                {
                    if (ay > ax * margin) lockedAxis = LockAxis.Vertical;
                }
                else // Vertical
                {
                    if (ax > ay * margin) lockedAxis = LockAxis.Horizontal;
                }
            }
            else
            {
                lockedAxis = (ax >= ay) ? LockAxis.Horizontal : LockAxis.Vertical;
            }

            return (lockedAxis == LockAxis.Horizontal)
                ? new Vector2(offset.x, 0f)
                : new Vector2(0f, offset.y);
        }

        // Pitch in degrees below horizontal: 0 = looking level, positive = looking down.
        float GetPitch()
        {
            return Mathf.Asin(Mathf.Clamp(-transform.forward.y, -1f, 1f)) * Mathf.Rad2Deg;
        }

        bool TryGetGroundPointAtScreenCenter(out Vector3 point)
        {
            Ray ray = cam.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0f));
            Plane plane = new Plane(Vector3.up, new Vector3(0f, groundPlaneY, 0f));
            if (plane.Raycast(ray, out float enter))
            {
                point = ray.GetPoint(enter);
                return true;
            }
            point = Vector3.zero;
            return false;
        }

        // --- Bounds -------------------------------------------------------------

        // Keeps the CAMERA inside its box (all three axes).
        void ClampToBounds()
        {
            if (boundsCollider == null) return;
            transform.position = ClampPointToBox(transform.position, boundsCollider);
        }

        // Keeps the look-at TARGET inside its box, correcting only horizontally so the
        // camera's height (and the on-plane target) are preserved.
        void ClampTargetToBounds()
        {
            if (targetBoundsCollider == null) return;
            if (!TryGetGroundPointAtScreenCenter(out Vector3 target)) return;

            Vector3 correction = ClampPointToBox(target, targetBoundsCollider) - target;
            correction.y = 0f; // target lives on the plane; never push the camera vertically
            transform.position += correction;
        }

        // Clamps a world point into a BoxCollider, working in the collider's local space
        // so a rotated or non-uniformly scaled box still works.
        static Vector3 ClampPointToBox(Vector3 world, BoxCollider box)
        {
            Transform t = box.transform;
            Vector3 local = t.InverseTransformPoint(world);

            Vector3 min = box.center - box.size * 0.5f;
            Vector3 max = box.center + box.size * 0.5f;
            local = Vector3.Max(min, Vector3.Min(max, local));

            return t.TransformPoint(local);
        }

        // --- Helpers ------------------------------------------------------------

        // Projects a vector onto the XZ plane and normalizes it.
        // Falls back gracefully if the camera is looking almost straight down.
        static Vector3 Flatten(Vector3 v)
        {
            v.y = 0f;
            return (v.sqrMagnitude > 1e-4f) ? (v.normalized) : (Vector3.zero);
        }
    }
}
